---
title: "EM_S23_Week5"
author: "Rosalee Elting"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Week 5 - Day 1

## Biomass example

```{r}
library(tidyverse)
library(MetBrewer)
library(rstan)
library(tidybayes)

sigma_site <- 50
sigma_plot <- 50 
n_site <- 8
n_plot <- 6
beta0_mean <- 400 
beta1 <- 200
#going to need another column in df called nit, that is repeat of 0 0 0 1 1 1 at each site. 
```

```{r}
biomass <- data.frame(
  site = rep(1:8, each = n_plot),
  plot = rep(1:6),
  nit = rep(c(rep(0, n_plot/2), rep(1, n_plot/2)), n_site),
  b_ij = NA
)
#Bij = Beta0,j + Beta1* Nit


#making site means using overall mean. 
site_mean <- rep(beta0_mean, n_site) + rnorm(n_site, 0, sigma_site)
#making data points using plot means
plot_mean <- rep(site_mean, each = n_plot) + rnorm(n_plot*n_site, 0, sigma_plot)

biomass$b_ij <- plot_mean + beta1*biomass$nit

#testing to see if it matches 
mean(biomass$b_ij[biomass$nit==1])
mean(biomass$b_ij[biomass$nit==0])

#plotting based on site
ggplot(biomass, aes(x=as.factor(nit), y = b_ij, col= as.factor(nit)))+ 
  geom_point()+
  facet_wrap(~as.factor(site))+
  theme_classic()

```

# Running Stan Code 
```{r}
library(rstan)

biomass_data <- list(n= nrow(biomass), n_site = as.integer(n_site), y= as.numeric(biomass$b_ij), site_id= biomass$site, nit = biomass$nit, beta1= beta1)

biomass_fit <- stan(file = "biomass_wnit.stan", data = biomass_data, iter = 1000, chains= 4)
print(biomass_fit)
```

# Commented Stan Code
Below is the stan code I've written, commented out but to have it in one location. 
```{r}
# data { 
#   int<lower=0> n; 
#   int<lower=0> n_site;
#   int<lower=0> beta1; 
#   vector<lower=0>  [n] y; 
#   int<lower=0>  site_id [n]; 
#   int<lower=0> nit [n];
# }
#   
# parameters { 
#   vector<lower=0> [n_site] mu_site_nit; //site level mean, with nit addition, length of 8
#   vector<lower=0> [n_site] mu_site_cntr; //site level mean, without nit addition, length of 8
#   real<lower=0> sigma_plot; //given value
#   real<lower=0>  sigma_site; //given value
#   real<lower=0> mu; //group level mean  for all treatments
# 
# }
# 
# 
#   
#   model { 
#     for( i in 1: n){
#       if (nit[i] == 1)
#           y[i] ~ normal(mu_site_nit, sigma_plot);
#       else
#           y[i] ~normal(mu_site_cntr, sigma_plot);
# }
#     mu_site_nit~ normal((mu + beta1), sigma_site); //eight means for each site's 3 plots with nitrogen
#     mu_site_cntr~ normal(mu, sigma_site); //eight means for each site's 3 plots without nitrogen 
#     mu ~ gamma(1, 0.001);  //this and subsequent rows are prior distribtuions for the parameters 
#     sigma_plot ~ normal(0,100); 
#     sigma_site ~ normal(0,100);
# }

```

# Visualizations 
```{r}
biomass_fit_summ<- summary(biomass_fit)

biomass_data <- data.frame(biomass_data)

mean_calc<- biomass_data %>%
  group_by(site_id) %>%
  summarise(meanB=mean(y), se=sd(y)/sqrt(6))

steps<- biomass_fit %>% 
  spread_draws(mu_site_nit[site_id])
  

ggplot(steps, aes(x=as.factor(site_id), y=mu_site_nit)) + 
  geom_violin()+
  geom_boxplot(width=0.1, color="grey", alpha=0.2) +
  geom_point(data=biomass_data, mapping = aes(x=as.factor(site_id), y=y ),  position = position_jitter(seed = 1, width = 0.2))+
  geom_point(data=mean_calc, mapping = aes(x=as.factor(site_id), y=meanB), color= "#3399FF")+
  xlab("Site")+
  ylab("Bioamss")+
  labs(title = "Complete Pooling")+
  theme_classic()
```

### Visualization 2
```{r}
ggplot(steps, aes(x=as.factor(site_id), y=mu_site_nit)) + 
  
  geom_boxplot(width=0.1, color="grey", alpha=0.5, outlier.shape = NA) +
  #geom_point(data=B, mapping = aes(x=as.factor(site), y=B_ij ),  position = position_jitter(seed = 1, width = 0.2))+
  geom_point(data=mean_calc, mapping = aes(x=as.factor(site_id), y=meanB), color="#3399FF")+
   geom_point(data=mean_calc, mapping = aes(x=as.factor(site_id), y=meanB+2.3*se), color="#3399FF")+
   geom_point(data=mean_calc, mapping = aes(x=as.factor(site_id), y=meanB-2.3*se), color="#3399FF")+
  xlab("Site")+
  ylab("Biomass")+
  labs(title = "Complete Pooling")+
  theme_classic()
```

